%% input mode visualization

for inc_mode=1:pcnt
%inc_mode=1;
pbm_ind=inc_mode;

% E-field

aGEy_xz=[aPG_Ey_xz(:,:,pbm_ind)]; 

aGEx_xz=[aPG_Ex_xz(:,:,pbm_ind)]; 

aGEz_xz=[aPG_Ez_xz(:,:,pbm_ind)]; 


% H-field

aGHy_xz=[aPG_Hy_xz(:,:,pbm_ind)]; 

aGHx_xz=[aPG_Hx_xz(:,:,pbm_ind)]; 

aGHz_xz=[aPG_Hz_xz(:,:,pbm_ind)]; 
                  
% figure(1); subplot(3,2,1); imagesc(zz/a,xx/a,(real(aGEx_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Ex-xz'); colorbar;
%            subplot(3,2,2); imagesc(zz/a,xx/a,(real(aGEy_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Ey-xz'); colorbar;
%            subplot(3,2,3); imagesc(zz/a,xx/a,(real(aGEz_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Ez-xz'); colorbar;
%            subplot(3,2,4); imagesc(zz/a,xx/a,(real(aGHx_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Hx-xz'); colorbar;
%            subplot(3,2,5); imagesc(zz/a,xx/a,(real(aGHy_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Hy-xz'); colorbar;
%            subplot(3,2,6); imagesc(zz/a,xx/a,(real(aGHz_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Hz-xz'); colorbar;
% 
figure(11);
% subplot(3,2,1); imagesc(zz/a,xx/a,(real(aGEx_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Ex-xz'); colorbar;
% subplot(3,2,2); imagesc(zz/a,xx/a,(real(aGEy_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Ey-xz'); colorbar;
% subplot(3,2,3); imagesc(zz/a,xx/a,(real(aGEz_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Ez-xz'); colorbar;
% subplot(3,2,4); imagesc(zz/a,xx/a,(real(aGHx_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Hx-xz'); colorbar;
% subplot(3,2,5); 
imagesc(zz/a,xx/a,(real(aGHy_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Hy-xz'); colorbar;
% subplot(3,2,6); imagesc(zz/a,xx/a,(real(aGHz_xz))); set(gca,'ydir','normal'); axis equal; axis([zz(1)/a zz(end)/a xx(1)/a xx(end)/a]); xlabel('z (in unit of a)'); ylabel('x (in unit of a)');title('aPG-Hz-xz'); colorbar;


           pause;
%             close all;
end;
% 
% [lx lz]=size(aGEx_xz);
% 
% axx=xx;
% x_inc=axx(2)-axx(1);
% azz=[0:z_inc:z_inc*(lz-1)];
% 
% 
% figure(1); imagesc(azz/a,axx/a,100*real(aGEy_xz));
% axis([azz(1)/a azz(lz)/a axx(1)/a axx(lx)/a ]);
% hold on;
% 
% for m=1:8
%     
%     for n=-4:4
%     
%     rectangle('Position',[m-r/a-0.5,n-r/a,2*r/a,2*r/a],'Curvature',[1,1],'LineWidth',2,'LineStyle','--','EdgeColor','w');
%         
%     end;
%     
% end;
% 
% 
%%

for inc_mode=1:mcnt
%inc_mode=1;
pbm_ind=inc_mode;

% E-field

aGEy_xz=[aNG_Ey_xz(:,:,pbm_ind) ... 
    aNG_Ey_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*aTz) ... 
    aNG_Ey_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*2*aTz)...
    aNG_Ey_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*3*aTz) ... 
    aNG_Ey_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*4*aTz)...
    aNG_Ey_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*5*aTz)...
    aNG_Ey_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*6*aTz) ... 
    aNG_Ey_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*7*aTz)]; 

aGEx_xz=[aNG_Ex_xz(:,:,pbm_ind) ... 
    aNG_Ex_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*aTz)...
    aNG_Ex_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*2*aTz)...
    aNG_Ex_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*3*aTz)...
    aNG_Ex_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*4*aTz)...
    aNG_Ex_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*5*aTz)...
    aNG_Ex_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*6*aTz)...
    aNG_Ex_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*7*aTz)...
    ]; 

aGEz_xz=[aNG_Ez_xz(:,:,pbm_ind)...
    aNG_Ez_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*aTz)...
    aNG_Ez_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*2*aTz)...
      aNG_Ez_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*3*aTz)...
    aNG_Ez_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*4*aTz)...
      aNG_Ez_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*5*aTz)...
    aNG_Ez_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*6*aTz)...
     aNG_Ez_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*7*aTz)...
    ]; 


% H-field

aGHy_xz=[aNG_Hy_xz(:,:,pbm_ind) ... 
    aNG_Hy_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*aTz) ... 
    aNG_Hy_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*2*aTz)...
    aNG_Hy_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*3*aTz) ... 
    aNG_Hy_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*4*aTz)...
    aNG_Hy_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*5*aTz)...
    aNG_Hy_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*6*aTz) ... 
    aNG_Hy_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*7*aTz)...
    ]; 

aGHx_xz=[aNG_Hx_xz(:,:,pbm_ind) ... 
    aNG_Hx_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*aTz)...
    aNG_Hx_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*2*aTz)...
    aNG_Hx_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*3*aTz)...
    aNG_Hx_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*4*aTz)...
    aNG_Hx_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*5*aTz)...
    aNG_Hx_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*6*aTz)...
    aNG_Hx_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*7*aTz)...
    ]; 

aGHz_xz=[aNG_Hz_xz(:,:,pbm_ind)...
    aNG_Hz_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*aTz)...
    aNG_Hz_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*2*aTz)...
      aNG_Hz_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*3*aTz)...
    aNG_Hz_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*4*aTz)...
      aNG_Hz_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*5*aTz)...
    aNG_Hz_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*6*aTz)...
     aNG_Hz_xz(:,:,pbm_ind)*exp(am_evalue(pbm_ind)*7*aTz)...
    ]; 
                  
figure(1); imagesc(abs(real(aGEx_xz))); title('aPG-Ex-xz'); colorbar;
figure(2); imagesc(abs(real(aGEy_xz))); title('aPG-Ey-xz'); colorbar;
figure(3); imagesc(abs(real(aGEz_xz))); title('aPG-Ez-xz'); colorbar;
% 
figure(4); imagesc(abs(real(aGHx_xz))); title('aPG-Hx-xz');colorbar;
figure(5); imagesc(abs(real(aGHy_xz))); title('aPG-Hy-xz');colorbar;
figure(6); imagesc(abs(real(aGHz_xz))); title('aPG-Hz-xz');colorbar;

pause;
end;